const ROUTES = {
  ROOT: "/",
  ABOUT: "/about",
  CARDS: "/cards",
  FAV_CARDS: "/fav-cards",
  MY_CARDS: "/my-cards",
  CARD_DETAILS: "/card-info",
  SIGNUP: "/signup",
  LOGIN: "/login",
  SANDBOX: "/sandbox",
  CREATE_CARD: "/create-card",
  EDIT_CARD: "/edit-card",
  EDIT_USER: "/edit-user",
  PROFILE: "/profile",
  USERS_PAGE: "/users-page",
  MORE_DETAILS: "/more-details",
};

export const SANDBOX_ROUTES = {
  COMPONENT: "component",
  TEMPLATE: "template",
  LOGIC: "logic",
  STYLES: "styles",
  LIFECYCLE: "lifecycle-hook",
  INITIAL: "initial",
  USE_STATE: "use-state-cycle",
  DID_MOUNT: "componentDidMount",
  DID_UPDATE: "useEffectDidUpdate",
  WILL_UNMOUNT: "useEffectWillUnmount",
  NO_DEPENDENCIES: "no-dependencies",
  LIFECYCLE_EXE: "exe",
  CUSTOM: "custom",
  CUSTOM_COUNTER: "counter",
  CUSTOM_NAME: "name",
  MEMOIZATION: "memoization",
  USECALLBACK: "useCallback",
  USEMEMO: "useMemo",
  CONTEXT: "context",
  NAME: "name",
  SNACK: "snack",
};

export default ROUTES;
